src/main/java/club/backingBeans/platform/ThemeBean.java
package club.backingBeans.platform;

import javax.ejb.Singleton;
import javax.inject.Named;

import club.DAO.platform.Theme;

@Named(value = "themeBean")
@Singleton
public class ThemeBean {
	
	private String primaryColorHEX;
	private String secondaryColorHEX;
	
	public ThemeBean() {
	}
	
	public Theme createThemeFromBean(){
		Theme theme = new Theme();
		theme.setId(1);
		theme.setPrimaryColorHex(primaryColorHEX);
		theme.setSecondaryColorHex(secondaryColorHEX);
		
		return theme;
	}
	
	
	public String getPrimaryColorHEX() {
		return primaryColorHEX;
	}
	public void setPrimaryColorHEX(String primaryColorHEX) {
		this.primaryColorHEX = primaryColorHEX;
	}
	public String getSecondaryColorHEX() {
		return secondaryColorHEX;
	}
	public void setSecondaryColorHEX(String secondaryColorHEX) {
		this.secondaryColorHEX = secondaryColorHEX;
	}
	
	public String getPrimaryColorHEXwithHash() {
		return "#"+getPrimaryColorHEX();
	}

	public String getSecondaryColorHEXwithHash() {
		return "#"+getSecondaryColorHEX();		
	}

}

src/main/webapp/WEB-INF/templates/main-template.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

<h:head >
	<meta name="charset" content="UTF-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>#{platformBean.title}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<h:outputStylesheet library="css" name="mantis.css"  />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"/>
	<h:outputScript library="js" name="jquery.js"/> 
	<h:outputScript library="js" name="script.js"/>    
</h:head>

<h:body>

	<style>
		 ul.navish{
			background-color: #{ themeBean.secondaryColorHEXwithHash };
			padding: 15px;
		 }
		 
		 ul.navish a:hover{
			color: #{ themeBean.primaryColorHEXwithHash };
		 }
				
		 .post-box{
			border: 2px solid #{ themeBean.primaryColorHEXwithHash };
			margin: 5px;
			width: 850px;
		 }
				
		 .post-entity{
			margin: 5px;
			padding: 5px;
		 }
				
		 .post-inner-box{
		 	color: gray;
			padding: 20px;
			float: left;		
			width: 500px;	
		 }
		 
		 .user-table {   
		   border:1px solid #000000;
		}

		 .user-table tr:nth-child(even) {   
			background: #eee;
		}
		
		.user-table .btn{
			font-size:10px;
			padding:2px;
		}
		
		.user-table-header {
		   text-align:center;
		   background:none repeat scroll 0 0 #B5B5B5;
		   border-bottom:1px solid #000000;  
		   padding:2px;
		}
		
		.user-table-odd-row {
		   text-align:center;
		   background:none repeat scroll 0 0 white;	
		}
		
		.user-table-even-row {
		   text-align:center;
		   background:none repeat scroll 0 0 white;
		}
	
	</style>
	
	<!-- include nav-bar -->
	<ui:include src="/WEB-INF/components/nav-bar.xhtml" />
	
	<!-- Main content goes here -->
	<div class="main-content">
		<ui:insert name="pageContent">
			<p>No content inserted</p>
		</ui:insert>
	</div>
	
</h:body>
	
</html>