src/main/java/club/backingBeans/news/CreateNewsBean.java
package club.backingBeans.news;

import java.sql.Timestamp;
import java.time.Instant;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import club.DAO.news.News;
import club.DAO.user.User;
import club.backingBeans.user.LoginUserBean;

@RequestScoped
@Named(value="createNewsBean")
public class CreateNewsBean extends NewsBean {
	

	@Inject @Named("loginUserBean")
	private LoginUserBean loginUserBean;
		
	public String submit() {
		return super.createAndRedirect();
	}
	
	@PostConstruct
	public void init() {
	}

	@Override
	public News updateFromFields() {		
		return null;
	}

	@Override
	public User getAuthor() {
		return loginUserBean.getUser();
	}

	@Override
	public News getFromFields() {
		News news = new News();
		news.setAuthor(this.getAuthor());  // note: must use this instead of super since getAuthor is overriden
		news.setTitle(super.getTitle());
		news.setText(super.getText());
		news.setHidden(false);
		news.setCreated(Timestamp.from(Instant.now()));
		return news;
	}

}

src/main/java/club/backingBeans/user/LoginUserBean.java
package club.backingBeans.user;

import javax.inject.Named;

import club.DAO.user.User;
import club.EJB.LoginHandlerable;
import club.EJB.interfaces.LocalUser;
import club.backingBeans.BasicFrontendBean;
import club.exceptions.LoginException;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;


@Named(value="loginUserBean")
@SessionScoped
public class LoginUserBean extends BasicFrontendBean implements Serializable, LoginHandlerable {
	
	private static final long serialVersionUID = -6514760360423746740L;

	private String username;
    private String password;
    private User loggedInUser;
    
	@EJB
	private LocalUser userEJB;

	public String doLogin() {
		
		try {
			userEJB.loginUser(username,password,this);
			return "home.xhtml?faces-redirect=true";				
		}
		catch(LoginException e) {
			super.addFacesMessage(e.getMessage());
			return "login";
		}
		
	}
	
	public String doLogout() {
		loggedInUser = null;
		return "index.xhtml?faces-redirect=true";
	}
	
	public void onLogin(User user) {
		this.loggedInUser = user;
	}
	
	
    public boolean isLoggedIn() {
    	return this.loggedInUser != null;
    }

	public String getUsername() {
		return username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}
	
	public User getUser() {
		return loggedInUser;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isValidLogin() {
		return loggedInUser != null;
	}

}

src/main/webapp/WEB-INF/components/comment-entity.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition>

	<!-- @param commentEntity. Comment -->
	<ui:param name="modalId" value="#{ commentEntity.id }"></ui:param>

	<h:panelGroup rendered="#{ !commentEntity.hidden }">

		<div class="comment-box">

			<p>
				<b>#{ commentEntity.user.fullName }:</b> #{ commentEntity.text }
			</p>
			<h:panelGroup rendered="#{not empty commentEntity.lastUpdated }">
				<i id="updated-comment">Last updated:
					#{commentEntity.lastUpdated}</i>
			</h:panelGroup>

			<h:panelGroup
				rendered="#{ commentEntity.user.email eq loginUserBean.user.email}">
				<h:form id="delete_comment" class="delete-comment">
					<h:commandLink style="float:right; padding: 4px;" action="#{ deleteCommentBean.submit(commentEntity.id ) }"	class="comment-method-link">
						<h:graphicImage value="resources/images/remove.png" />
						<f:param name="id" value="#{ commentEntity.post.id }" />
					</h:commandLink>
				</h:form>
			</h:panelGroup>

			<p:commandLink style="float:right;" class="comment-method-link"
				rendered="#{ commentEntity.user.email eq loginUserBean.user.email }"
				type="button" onclick="PF(#{ modalId }).show();">
				<h:graphicImage value="resources/images/update.png" />
			</p:commandLink>
			<p:dialog header="Update comment" widgetVar="#{ modalId }"
				modal="true" height="300">

				<form action="/clubproject/update-comment" method="post">
					<input type="hidden" name="comment_id"
						value="#{ commentEntity.id }" />
					<textarea name="text">#{ commentEntity.text }</textarea>
					<input type="submit" value="Update comment" />
				</form>

			</p:dialog>
			<div style="clear: both;"></div>

		</div>

	</h:panelGroup>
</ui:composition>

</html>

src/main/webapp/WEB-INF/components/comment-list-compact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<!-- @param commentList. List<Comment>-->
	
	<ui:repeat var="c" value="#{commentList}">
		<!-- TODO: fix a param to tell if this render check should be used. Or even better. define the method in root page (news.html) -->
		<h:panelGroup rendered="#{commentListLimitBean.render(c,3)}">
			<ui:include src="/WEB-INF/components/comment-entity.xhtml">
				<ui:param name="commentEntity" value="#{ c }"></ui:param>
			</ui:include>
		</h:panelGroup>
	</ui:repeat>
					
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/comment-list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<!-- @param commentList. List<Comment>-->
	
	<ui:repeat var="c" value="#{ commentList }">
		<ui:include src="/WEB-INF/components/comment-entity.xhtml">
			<ui:param name="commentEntity" value="#{ c }"></ui:param>
		</ui:include>
	</ui:repeat>
	
	
	<ui:include src="/WEB-INF/components/do-comment.xhtml">
		<ui:param name="postEntity" value="#{ postEntity }"></ui:param>
	</ui:include>	
			
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/login-form.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
		
	<h1>Login: </h1>
	<h:form id="login_user_form">

		<table class="form-wrapper">
			<tr>
				<td>
					<h:messages styleClass="messages">
						<h:message for="login_user_form"></h:message>
					</h:messages>					
				</td>
			</tr>
			<tr>
				<td>
					<table class="standard-form">
						<tr>
							<th><h:outputLabel for="email">Email:</h:outputLabel></th>
							<td><h:inputText id="email" value="#{ loginUserBean.username }" required="true" label="Email"/></td>
						</tr>
						<tr>
							<th><h:outputLabel for="password">Password:</h:outputLabel></th>
							<td><h:inputSecret id="password" value="#{ loginUserBean.password }" required="true" label="Password"/></td>
						</tr>
						<tr>
							<td class="submit" colspan="2">
								<h:commandButton class="btn" value="Login user" action="#{ loginUserBean.doLogin() }" />
							</td>
						</tr>					
					</table>
				</td>
			</tr>		
		</table>
	</h:form>
	
	No account? <h:link outcome="register-user">Click here to create account</h:link> 
	
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/nav-bar.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition>

	<div class="navbarish">
	  <div class="container-fluidish">
	    <div class="navbar-headerish">
	    
	    	<h:link class="navbar-brandish" outcome="index">#{ platformBean.title }</h:link>
	    
	    
	    </div>
	    
	    <ul class="navish">
	      	<h:panelGroup rendered="#{loginUserBean.validLogin}">
		      	<li><h:link outcome="home">Home</h:link></li>
	      		<li><h:link outcome="news-list">News</h:link></li>
	      		<li><h:link outcome="events-list">Events</h:link></li>
	      		<li><h:link outcome="chat">Chat</h:link></li>
			</h:panelGroup>
	      	      		
	      	<h:panelGroup rendered="#{loginUserBean.user.admin}">
				<li><h:link outcome="configure-platform">Configure platform</h:link></li>
				<li><h:link outcome="user-management">User management</h:link></li>
				<li><h:link outcome="create-news">Create News</h:link></li>
				<li><h:link outcome="create-event">Create Event</h:link></li>
			</h:panelGroup>
	      		
	      	<h:panelGroup rendered="#{loginUserBean.validLogin}">
		    	<li class="logout-link">
					<h:form id="logout_user_form">
		    			<h:commandLink value="Logout user" action="#{ loginUserBean.doLogout() }" />
					</h:form>
				</li>
				<li class="logged-in-as-link">Logged in as: <h:link outcome="user-profile">#{ loginUserBean.user.fullName }</h:link></li>
			</h:panelGroup>
	      
	      	<!-- <h:panelGroup rendered="#{!loginUserBean.validLogin}">
	    		<li class="not-logged-in">Not logged in</li>
		 	</h:panelGroup>-->
	     
	    </ul>
	  </div>
	</div>
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/news-entity-update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<p>This p-tag is the only visible thing in this component</p>
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/platform-information.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<h1>#{platformBean.title}</h1>
	<p>#{platformBean.description}</p>
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-entity-event-update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	>

<ui:composition>
	<h1>Manage event: </h1>
				
	<h:form id="update_event_form">

		<table class="form-wrapper">
			<tr>
				<td>
					<h:messages styleClass="messages">
						<h:message for="update_event_form"></h:message>
					</h:messages>	
				</td>
			</tr>
			<tr>
				<td>

					<table class="standard-form">
						<tr>
							<th>
								<h:outputLabel for="event_title">Event title:</h:outputLabel>							
							</th>
							<td>
							   	<h:inputText id="event_title" value="#{ eventUpdateBean.title }" required="true" label="Event Title"/>
							</td>
						</tr>
						<tr>
							<th>
							   	<h:outputLabel for="event_text">Event description:</h:outputLabel>
							
							</th>
							<td>
		   						<h:inputTextarea id="event_text" value="#{ eventUpdateBean.text }" required="true" label="Event Description"/>							
							</td>
						</tr>
						<tr>
							<th>
								<h:outputLabel for="event_durationInMinutes">Event duration:</h:outputLabel>
							</th>
							<td>
		   						<h:inputText id="event_durationInMinutes" value="#{ eventUpdateBean.durationInMinutes }" required="true" label="Event Duration"/>
							</td>
						</tr>
						<tr>
							<td colspan="2" class="submit">
								<h:commandButton class="btn" action="#{ eventUpdateBean.submit() }" value="Update event post">
									<f:param name="id" value="#{ eventUpdateBean.id }"></f:param>
								</h:commandButton>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</h:form>
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-entity-event.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<ui:composition>
	<!-- @param eventEntity. News -->

		<div class="post-box">
			<div class="post-inner-box">
			
				<h5>#{ eventEntity.title }</h5>
	 			<p class="time">#{eventWhenFormater.render(eventEntity)}</p>
				<p>#{ eventEntity.text }</p>
					
				<h:form id="attend_event_form">
					<h:panelGroup rendered="#{ includeAttendButton }">
						<h:commandButton class="btn" id="attend" value="Going" action="#{ addAttendantOnEventBean.submit() }">
							<f:param name="id" value="#{ eventEntity.id }"></f:param>
						</h:commandButton>
					
					</h:panelGroup>	
					<h:panelGroup rendered="#{ includeUnAttendButton }">
						<h:commandButton class="btn" id="unAttend" value="Not Going" action="#{ removeAttendantOnEventBean.submit() }">
							<f:param name="id" value="#{ eventEntity.id }"></f:param>	
						</h:commandButton>
					</h:panelGroup>				
				</h:form>

				<h:panelGroup rendered="#{ compactCommentList }">

					<ui:include src="/WEB-INF/components/comment-list-compact.xhtml">
						<ui:param name="commentList" value="#{ eventEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ eventEntity }"></ui:param>
					</ui:include>

				</h:panelGroup>

				<h:panelGroup rendered="#{ !compactCommentList }">
					<ui:include src="/WEB-INF/components/comment-list.xhtml">
						<ui:param name="commentList" value="#{ eventEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ eventEntity }"></ui:param>
					</ui:include>
				</h:panelGroup>

				<p><i><h:outputText value="#{eventEntity.created}"><f:convertDateTime pattern="yyyy-MM-dd HH:mm" /></h:outputText> </i></p>
				<p><i>#{ eventEntity.author.fullName }</i></p>

				<h:link rendered="#{ includeReadMoreBtn }" outcome="post-details" value="Read more" includeViewParams="true">		
				  <f:param name="id" value="#{ eventEntity.id }"></f:param>		
				</h:link>

			</div>
			<div class="attendants">
				<h:panelGroup rendered="#{ eventEntity.attendees.size() > 0 }">
					<h4>#{ eventEntity.attendees.size() } Going</h4>
					<ul>
						<ui:repeat var="a" value="#{ eventEntity.attendees }">
							<li>#{ a.fullName }</li>
						</ui:repeat>				
					</ul>
				</h:panelGroup>
				<h:panelGroup rendered="#{ eventEntity.attendees.size() == 0 }">
					<h4>No one's going</h4>
				</h:panelGroup>
			</div>
			<div class="end"></div>
		</div>
		
		<script type="text/javascript">
		/* <![CDATA[ */

			function dropdown_function() {
			    document.getElementById("myDropdown").classList.toggle("show");
			}
			
			window.onclick = function(event) {
			  if (!event.target.matches('.dropbtn')) {
			
			    var dropdowns = document.getElementsByClassName("dropdown-content");
			    for (var i = 0; i < dropdowns.length; i++) {
			      var openDropdown = dropdowns[i];
			      if (openDropdown.classList.contains('show')) {
			        openDropdown.classList.remove('show');
			      }
			    }
			  }
			}
			/* ]]> */
		</script>
			
	
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-entity-news-update.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<h1>Manage news: </h1>
				
	<h:form id="update_news_form">

		<table class="form-wrapper">
			<tr>
				<td>
					<h:messages styleClass="messages">
						<h:message for="update_news_form"></h:message>
					</h:messages>	
				</td>				
			</tr>			
			<tr>
				<td>
					<table class="standard-form">
						<tr>
							<th><h:outputLabel for="news_title">News title:</h:outputLabel></th>
							<td><h:inputText id="news_title" value="#{ newsUpdateBean.title }" required="true" label="News Title"/></td>
						</tr>
						<tr>
							<th><h:outputLabel for="news_text">News description:</h:outputLabel></th>
							<td><h:inputTextarea id="news_text" value="#{ newsUpdateBean.text }" required="true" label="News Description"/></td>
						</tr>
						<tr>
							<td colspan="2">
								<h:commandButton class="btn" action="#{ newsUpdateBean.submit() }" value="Update news post">
									<f:param name="id" value="#{ newsUpdateBean.id }"></f:param>
								</h:commandButton>								
							</td>
						</tr>
					</table>
				</td>				
			</tr>			
		</table>
	
	</h:form>
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-entity-news.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<!-- @param newsEntity. News -->

		<div class="post-box">
			<div class="post-inner-box">
			
				<h5>#{ newsEntity.title }</h5>
				<p>#{ newsEntity.text }</p>
				
				<h:panelGroup rendered="#{ compactCommentList }">

					<ui:include src="/WEB-INF/components/comment-list-compact.xhtml">
						<ui:param name="commentList" value="#{ newsEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ newsEntity }"></ui:param>
					</ui:include>

				</h:panelGroup>

				<h:panelGroup rendered="#{ !compactCommentList }">

					<ui:include src="/WEB-INF/components/comment-list.xhtml">
						<ui:param name="commentList" value="#{ newsEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ newsEntity }"></ui:param>
					</ui:include>

				</h:panelGroup>

				<p><i><h:outputText value="#{newsEntity.created}"><f:convertDateTime pattern="yyyy-MM-dd HH:mm" /></h:outputText> </i></p>
				<p><i>#{ newsEntity.author.fullName }</i></p>

				<h:link rendered="#{ includeReadMoreBtn }" outcome="post-details" value="Read more" includeViewParams="true">		
				  <f:param name="id" value="#{ newsEntity.id }"></f:param>		
				</h:link>

				
			</div>
			<div class="end"></div>
		</div>
		
			
	
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-entity.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<!-- @param postEntity. Post -->

		<div class="post-box">
			<div class="post-inner-box">
			
				<h5>#{ postEntity.title }<span> created: #{postEntity.created}</span></h5>
				<p>#{ postEntity.text }</p>
				<p>#{ postEntity.author.fullName }</p>
				
				<h:link rendered="#{ includeReadMoreBtn }" outcome="post-details" value="Read more" includeViewParams="true">		
				  <f:param name="id" value="#{ postEntity.id }"></f:param>		
				</h:link>

				<h:panelGroup rendered="#{ compactCommentList }">

					<ui:include src="/WEB-INF/components/comment-list-compact.xhtml">
						<ui:param name="commentList" value="#{ postEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ postEntity }"></ui:param>
					</ui:include>

				</h:panelGroup>

				<h:panelGroup rendered="#{ !compactCommentList }">

					<ui:include src="/WEB-INF/components/comment-list.xhtml">
						<ui:param name="commentList" value="#{ postEntity.comments }"></ui:param>
						<ui:param name="postEntity" value="#{ postEntity }"></ui:param>
					</ui:include>

				</h:panelGroup>

			</div>
		</div>
		
			
	
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/post-list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<!-- @param postList. List<Post>-->
	
	<ui:repeat var="p" value="#{postList}">
		<h:panelGroup rendered="#{ p['class'].getSimpleName() eq 'News'}">
			<ui:include src="/WEB-INF/components/post-entity-news.xhtml">
				<ui:param name="newsEntity" value="#{ p }"></ui:param>
				<ui:param name="includeReadMoreBtn" value="#{ true }"></ui:param>
				<ui:param name="compactCommentList" value="#{ true }"></ui:param>
			</ui:include>
		</h:panelGroup>
		
		<h:panelGroup rendered="#{ p['class'].getSimpleName() eq 'Event'}">
			<ui:include src="/WEB-INF/components/post-entity-event.xhtml">
				<ui:param name="eventEntity" value="#{ p }"></ui:param>
				<ui:param name="includeReadMoreBtn" value="#{ true }"></ui:param>
				<ui:param name="compactCommentList" value="#{ true }"></ui:param>
			</ui:include>
		</h:panelGroup>	
	</ui:repeat>
	
</ui:composition>
</html>

src/main/webapp/WEB-INF/components/user-management-list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

<ui:composition>

	<!-- @param List<User> users  -->
	
	<h:dataTable value="#{ users }" var="u" rendered="#{ users.size() > 0 }"
		styleClass="user-table"
		headerClass="user-table-header"
		rowClasses="user-table-odd-row,user-table-even-row">
		<h:column>
			<f:facet name="header"> First name </f:facet>
			<p>#{u.firstName}</p>
		</h:column>
		<h:column>
			<f:facet name="header"> Last name </f:facet>
			<p>#{u.lastName}</p>
		</h:column>
		<h:column>
			<f:facet name="header"> Email </f:facet>
			<p>#{u.email}</p>
		</h:column>
		<h:column>
			<f:facet name="header"> Birthday / Personalnumber </f:facet>
			<p>#{u.birthday}</p>
		</h:column>
		<h:column>
			<f:facet name="header"> Is admin </f:facet>
			<p>#{u.admin}</p>
		</h:column>
		
		<h:column>
			<h:form>
				<h:panelGroup rendered="#{show_deny_option}">
					<h:commandButton class="btn" value="Deny" action="#{ userManagementBean.denyApprovement() }">				
						<f:setPropertyActionListener value="#{ u }" target="#{ userManagementBean.selectedUser }"></f:setPropertyActionListener>
					</h:commandButton>
				</h:panelGroup>
				<h:panelGroup rendered="#{show_grant_option}">
					<h:commandButton class="btn" value="Approve" action="#{ userManagementBean.grantApprovement() }">				
						<f:setPropertyActionListener value="#{ u }" target="#{ userManagementBean.selectedUser }"></f:setPropertyActionListener>
					</h:commandButton>
				</h:panelGroup>				
				<h:panelGroup rendered="#{ true }">
					<h:commandButton class="btn" value="Switch Admin state" action="#{ userManagementBean.switchAdminState() }">				
						<f:setPropertyActionListener value="#{ u }" target="#{ userManagementBean.selectedUser }"></f:setPropertyActionListener>
					</h:commandButton>
				</h:panelGroup>				
			</h:form>
		</h:column>

	</h:dataTable>
	
	
</ui:composition>

</html>